/*
;/doc/ ************************************************************************
;
; DllMain: Migration DLLMain
;
; Synopsis of Service:
;
; #include "services.h"                Services information for Migration DLLs
;
; BOOL DllMain                         Mscomctl migration DllMain
; (
;    HANDLE hModule                    A handle to the DLL module
;    DWORD  reason                     Code indicating why call is being made
;    LPVOID lpReserved                 Reason-specific parameter
; )
;
; Description of Service:
;
; This is the entry point into a dynamic-link library (DLL) that implements
; a set of migration event handlers for events generated by the translation
; tool. When the translation tool loads a refactoring specification whose
; <b>Refactor</b> statement contains the attribute <b>dllName="Migration.dll"</b>
; then this entry point in the <b>Migration DLL</b> is called. This is a
; MicroSoft specific service that performs no application specific operations,
; and is thus identical for all migration DLLs.
;
; MicroSoft says "Warning, There are serious limits on what you can do in a DLL
; entry point. To provide more complex initialization, create an initialization
; routine for the DLL. You can require applications to call the initialization
; routine before calling any other routines". In this case of this system that
; initialization routine is <b>InitializeServices</b> which is described
; elsewhere in this documentation.
;
; Properties of Service:
;
; hModule          A handle to the DLL module. The value is the base address of
;                  the DLL. The HINSTANCE of a DLL is the same as the HMODULE
;                  of the DLL, so hinstDLL can be used in calls to functions
;                  that require a module handle. It is not used here.
;
; reason           The reason code that indicates why the DLL entry-point
;                  function is being called. This parameter can be one of the
;                  following values -- DLL_PROCESS_ATTACH, DLL_THREAD_ATTACH.
;                  DLL_THREAD_DETACH, DLL_PROCESS_DETACH. It is used here only
;                  to produce the appropriate return value.
;
; lpReserved       A reason-specific parameter not used here.
;
; Return Value from Service:
;
; This is described by MicroSoft as follows. When the system calls the DllMain
; function with the DLL_PROCESS_ATTACH value, the function returns TRUE if it
; succeeds or FALSE if initialization fails. (Here TRUE is returned). If the
; return value is FALSE when DllMain is called because the process uses the
; LoadLibrary function, LoadLibrary returns NULL. (The system immediately calls
; your entry-point function with DLL_PROCESS_DETACH and unloads the DLL.) If
; the return value is FALSE when DllMain is called during process
; initialization, the process terminates with an error. To get extended error
; information, call GetLastError. When the system calls the DllMain function
; with any value other than DLL_PROCESS_ATTACH, the return value is ignored.
;
;/doc/ ************************************************************************
*/
#include "stdafx.h"
#define SERVICES                  /* Gives access to virtual service types */
#include "platform.h"
#include "ADSservices.h"

IntegerService* iServices = NULL;
HandleService*  hServices = NULL;
VoidService*    vServices = NULL;
DoubleService*  dServices = NULL;
StringService*  sServices = NULL;

BOOL APIENTRY DllMain(HANDLE hModule,DWORD reason,LPVOID lpReserved)
{
   hModule;
   lpReserved;
 
   switch(reason)
   {
   case DLL_PROCESS_ATTACH:
      return TRUE;
   case DLL_THREAD_ATTACH:
     return FALSE;
   case DLL_THREAD_DETACH:
     return FALSE;
   case DLL_PROCESS_DETACH:
     return TRUE;
   }
   return FALSE;
}

